version: '3.9'
services:
  teamcity-server-clean:
    image: jetbrains/teamcity-server:2019.1.1
    platform: linux/amd64
    ports:
      - "8111:8111"
    restart: always
    volumes:
      - ./tc_data/teamcity_clean/data:/data/teamcity_server/datadir
      - ./tc_data/teamcity_clean/logs:/opt/teamcity/logs
    networks:
      - teamcity-network

  teamcity-agent-clean:
    image: jetbrains/teamcity-agent:2019.1.1
    platform: linux/amd64
    restart: always
    volumes:
      - ./tc_data/teamcity_clean/data:/data/teamcity_server/datadir
      - ./tc_data/teamcity_clean/logs:/opt/teamcity/logs
    environment:
      - SERVER_URL=teamcity-server-clean:8111
    networks:
      - teamcity-network

networks:
  teamcity-network:
    external: true